import argparse, json, time, wave, pathlib
import numpy as np
import sounddevice as sd
import soundfile as sf
import matplotlib.pyplot as plt
from scipy import signal, fft
import ldpc_jossy as ldpc_jossy
import math
import time
import pickle

start_time = time.time()

# Parameters
FS = 48_000  # audio sample-rate (Hz)
FFT_LEN = 8192  # size of one OFDM symbol (must be even)
CP_LEN = FFT_LEN // 4  # cyclic-prefix length
CHIRP_LEN_S = 1 / 2  # chirp duration (seconds)
SILENCE_LEN_S = 1.0
F0, F1 = 3000, 0  # chirp start / end frequencies (Hz)
TX_REPS = 5  
WAV_TX = 'tx_sequence.wav'
WAV_RX = 'rx_recording.wav'
PILOT_NPY = 'pilot_symbols.npy'
DATA_NPY = 'data_symbols.npy'  # Will now store frequency-domain data symbols
COLMAP_NPY = 'colour_map.npy'
CHAN_NPY = 'channel_estimate.npy'
PILOT_TIME_NO_CP_NPY = "time_pilot_blocks_no_cp.npy"
OUTPUT          = 'output_dict.pkl'

FILE_BIN_DIR = "3000/example.npy"
FILE_BIN = np.load(FILE_BIN_DIR) #   To be generated by the file encoder


CHIRP_ATTEN = 0.80  # scale applied to both chirps
TARGET_PEAK = 0.80  # peak of every OFDM block after scaling
#LENGTH_TOL = 10
LENGTH_TOL = 50


Q_COL = {(0, 0): '#d62728',  # red
         (0, 1): '#1f77b4',  # blue
         (1, 1): '#2ca02c',  # green
         (1, 0): '#ff7f0e'}  # orange


# LDPC params
LDPC_STD = "802.11n"
LDPC_RATE = "1/2"
LDPC_Z = 81
LDPC_N = 24 * LDPC_Z         # = 1944
LDPC_K = LDPC_N // 2         # = 972

c = ldpc_jossy.code(LDPC_STD, LDPC_RATE, LDPC_Z)

# Sanity‐check: each OFDM symbol will carry TWO codewords, each of length=LDPC_N=1944 bits,
# so total QPSK symbols per OFDM = 2*(LDPC_N/2) = 2*972 = 1944.  We must have <= 4095 available subcarriers.
assert 2 * (LDPC_N // 2) <= (FFT_LEN // 2 - 1)

#-----------------------------------------------------------------------------------------#

def num_data_block(binary_sequence: np.ndarray):
    ldpc_blocks = math.ceil(len(binary_sequence) / c.K)
    print("Number of LDPC blocks required by source: ", ldpc_blocks)
    data_blocks = math.ceil(ldpc_blocks / 2)
    print("Number of data blocks required to carry source: ", data_blocks)
    return int(data_blocks)

def ldpc_encoder(binary_sequence: np.ndarray):
    orig_len = binary_sequence.size
    print("Length of source: ", orig_len)
    pad_len = (-orig_len) % c.K
    print("Source padding length for LDPC: ", pad_len)
    if pad_len:
        bits = np.pad(binary_sequence, (0, pad_len), 'constant', constant_values=0)
    else:
        bits = binary_sequence
    num_blocks = bits.size // c.K
    print("Number of LDPC blocks synthesised: ", num_blocks)

    blocks = bits.reshape(num_blocks, c.K)

    ldpc_blocks = []
    for block in blocks:
        ldpc_blocks.append(c.encode(block))
    
    print("Shape of raw output post LDPC: ", np.array(ldpc_blocks).shape)
    
    flat = np.array(ldpc_blocks).ravel()
    paired = flat.reshape(-1, 2)
    print("Shape of LDPC output, as bit pairs", paired.shape)
    return paired, bits

def ldpc_insert(prefilled: np.array, ldpc_data: np.array):
    print("Prefilled data block array shape", prefilled.shape)
    print("LDPC data block shape", ldpc_data.shape)
    A, Lx, C  = prefilled.shape
    B, Ly, C2 = ldpc_data.shape
    assert C == C2 == 2

    start = 200
    block_size = Ly

    data = prefilled.copy()
    n_full_pairs = B // 2

    for i in range(min(n_full_pairs, A)):
        data[i, start:start+block_size, :] = ldpc_data[2*i] 
        data[i, start+block_size:start+block_size+block_size, :] = ldpc_data[2*i]

    if (B % 2 == 1) and (n_full_pairs < A):
        data[n_full_pairs, start:start+block_size, :] = ldpc_data[-1]
    return data

def generate_chirp(f0=F0, f1=F1, dur=CHIRP_LEN_S) -> np.ndarray:
    t = np.linspace(0, dur, int(dur * FS), endpoint=False)
    k = (f1 - f0) / dur  # Sweep rate (Hz/s)
    phase = 2 * np.pi * (f0 * t + 0.5 * k * t**2)
    signal = np.sin(phase)
    return (CHIRP_ATTEN * signal).astype(np.float32)

def random_bitpairs(n, seed_no=42):
    np.random.seed(seed_no)
    return np.random.randint(0, 2, size=(n, 2), dtype=np.int8)

def qpsk_gray(bitpairs):
    mapping = {(0, 0): 1 + 1j, (0, 1): 1 - 1j, (1, 1): -1 - 1j, (1, 0): -1 + 1j}
    syms = np.array([mapping[tuple(b)] for b in bitpairs], np.complex64)
    colours = np.array([Q_COL[tuple(b)] for b in bitpairs])
    return syms, colours  # return colours to replicate later

def to_real_ofdm_block(useful_freq_symbols, n=FFT_LEN):
    half = n//2
    X = np.zeros(n, np.complex64)
    X[1:half]   = useful_freq_symbols
    X[half+1:]  = np.conj(useful_freq_symbols[::-1])
    x = fft.ifft(X).real.astype(np.float32)

    # This function doesn't normalise (produced by Max), compared to the version Steve and Phil uses
    # Intentionally used to match the receiver Max made
    return x

def add_cyclic_prefix(x: np.ndarray, cp_len: int = CP_LEN) -> np.ndarray:
    return np.concatenate([x[-cp_len:], x])

def prepare_tx_sequence(plot=False) -> dict:
    # ------------- build pieces -------------
    silence = np.zeros(int(SILENCE_LEN_S * FS), np.float32)
    chirp_up = generate_chirp(F0, F1, CHIRP_LEN_S)
    chirp_down = generate_chirp(F1, F0, CHIRP_LEN_S)

    n_qpsk = FFT_LEN // 2 - 1

    num_data_blocks = num_data_block(FILE_BIN)
    block_groups = math.ceil(num_data_blocks / 4)
    print("Number of block groups needed: ", block_groups)

    data_filler = np.random.RandomState(seed=24)
    prefilled_data = data_filler.randint(0, 2, size=(int(4 * block_groups), n_qpsk, 2), dtype=np.int8) # Shape = (data blocks needed, 4095, 2)

    ldpc_bit_pairs, padded_payload_bin = ldpc_encoder(FILE_BIN)
    ldpc_bit_pairs_insert = ldpc_bit_pairs.reshape(int(ldpc_bit_pairs.shape[0] / c.K), c.K, 2) # Shape = (padded length / 972, 972, 2)

    data_blocks_bin = ldpc_insert(prefilled_data, ldpc_bit_pairs_insert)
    data_block_freq = []
    data_blocks_time = []
    for block in data_blocks_bin: # Each block is (4095, 2)
        qpsk, _ = qpsk_gray(block)
        data_block_freq.append(qpsk)
        data_blocks_time.append(to_real_ofdm_block(qpsk)) # Each QPSK is (4095), each time domain data block is (8192); data_blocks_time has shape (data blocks needed, 8192)

    # print("LDPC inserted bit pair array shape: ", np.array(data_blocks_bin).shape) # Test point
    # print("LDPC inserted frequency data block array shape: ", np.array(data_block_freq).shape) # Test point
    # print("LDPC inserted time data block array shape: ", np.array(data_blocks_time).shape) # Test point

    # ---------- LDPC insertion complete ----------

    # ------------- build sequence --> 'payload' list will contain TD blocks WITHOUT CP -------------

    pilot_long_bits = random_bitpairs(n =(n_qpsk * (block_groups + 1))) # +1 just in case there isn't enough pilots

    time_pilot_blocks_no_cp = []
    pilot_freq_symbols = []
    pilot_colours = []

    for pilot in range(block_groups + 1): # Using Max's transmitter
        # print("Pilot chopping --------------------") # Test point
        pilot_bits = pilot_long_bits[pilot * n_qpsk : (pilot + 1) * n_qpsk]
        # print("Number of pilot bit pairs", np.array(pilot_bits).shape) # Test point
        freq_pilot, colour = qpsk_gray(pilot_bits)
        # print("Number of pilot frequency symbols", np.array(freq_pilot).shape) # Test point
        pilot_freq_symbols.append(freq_pilot)
        pilot_colours.append(colour)
        block_no_cp = to_real_ofdm_block(freq_pilot)
        # print("Number of pilot time signals", np.array(block_no_cp).shape) # Test point
        time_pilot_blocks_no_cp.append(block_no_cp)

    

    np.save(COLMAP_NPY, np.array(pilot_colours, dtype=object)) # Using Max's transmitter
    np.save(PILOT_NPY, pilot_freq_symbols) # Using Max's transmitter
    np.save(PILOT_TIME_NO_CP_NPY, time_pilot_blocks_no_cp) # Using Max's transmitter

    payload = []  # no CP
    payload_type = []

    for i in range(block_groups):
        # print(f"{i}th iteration in the number of block groups") # Test point
        payload.append(time_pilot_blocks_no_cp[i])
        payload_type.append('pilot')
        for j in range(4):
            # print(f"{i}th and {j}th iteration in the data block") # Test point
            payload.append(data_blocks_time[i * 4 + j])
            payload_type.append('data')

    # print("Payload types: ", payload_type) # Test point

    sequence = [
        silence,
        chirp_up,
        *payload,  # Unpacks TD blocks (pilots & data), all WITHOUT CP
        chirp_down,
        silence
    ]

    for i in range(2, len(sequence) - 2):
        sequence[i] = add_cyclic_prefix(sequence[i])
    
    waveform_unscaled = np.concatenate(sequence)
    if np.max(np.abs(waveform_unscaled)) > 0:
        global_scale = TARGET_PEAK / np.max(np.abs(waveform_unscaled))
        waveform_scaled = (waveform_unscaled * global_scale).astype(np.float32)
    else:
        waveform_scaled = waveform_unscaled.astype(np.float32)

    sf.write(WAV_TX, waveform_scaled, FS)

    # ------------- plot function -------------
    if plot:
        plt.figure(figsize=(10, 3))
        plt.plot(np.concatenate(sequence), lw=0.7)  # Plot concatenated sequence
        plt.title("Transmit waveform (time domain)")
        plt.xlabel("sample")
        plt.ylabel("amplitude")
        plt.tight_layout()
        plt.show()

    # ------------- Correct calculation for total_ofdm_length -------------
    calculated_total_ofdm_length = len(payload_type) * (FFT_LEN + CP_LEN)

    """
    for i, syms in enumerate(data_block_freq): # Test point
        print(f" data block {i}: {len(syms)} symbols")
    """

    # ------------- flat dictionary ---> key{waveform} is a flattened sequence, key{waveform_blocks} is unflattened -------------
    info = {
        "leading_silence_samples": len(silence),
        "chirp_samples": len(chirp_up),  # Length of chirp signal (no CP)
        "ofdm_block_len": FFT_LEN,
        "ofdm_block_len_with_cp": (len(sequence[2])),  # Length of first payload block (with CP)
        "cp_len": CP_LEN,
        # sanity‐check: is the very first payload block real?
        "block_real?": np.isrealobj(sequence[2]),  # sequence[0]=silence, [1]=chirp_up, [2]=first pilot+CP
        "total_ofdm_length": calculated_total_ofdm_length,
        "final_len": len(np.concatenate(sequence)),
        "no_of_payload_blocks": len(payload_type),
        "waveform_blocks": sequence,
        "payload_type_list": payload_type,
        #"payload_data_blocks": np.array(data_freq_symbols_),
        "payload_data_blocks": np.stack(data_block_freq),

        "payload_info_bits" : padded_payload_bin

    }
    print("Padded file binary length: ", len(padded_payload_bin))
    return {"waveform": np.concatenate(sequence), **info}

with open(OUTPUT, 'wb') as fp:
    pickle.dump(prepare_tx_sequence(plot=True), fp)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed Time: {elapsed_time} seconds")



if __name__ == "__main__":

    pass

# def play_audio(sig:np.ndarray, fs:int=FS): # Definition was in original but commented out
# sd.play(sig, fs); sd.wait()


## SHOULD OUTPUT:
#colour_map.npy        ←  length=4095 array of ints (unchanged)
#data_symbols.npy      ←  shape = (TX_REPS, 1944)   # ← changed!
#pilot_symbols.npy     ←  shape = (4095,)          # unchanged
#tx_sequence.wav       ←  real-valued samples (unchanged format)

#